services:
  mysql:
    image: mysql:9.0.1
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ronoyaro
      MYSQL_PASSWORD: dev
    ports:
      - "3306:3306"
    volumes:
      - user_service-db:/var/lib/mysql
volumes:
  user_service-db: