spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_service?useTimeZone=true&serverTimeZone=UTC&createDatabaseIfNotExist=true
    username: root
    password: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true